services:
  web:
    build: .
    links:
      - redis
      - rabitmq
      - worker
    depends_on:
      - redis
      - rabitmq
      - worker
    environment:
      FLASK_ENV: "development"
      APP_BROKER_URI: "pyamqp://guest@rabitmq:5672"
      APP_BACKEND: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ./artifacts:/code/artifacts
    ports:
      - "6000:5000"
    entrypoint: poetry
    command: run gunicorn app:app -w 3 -p 8000
  redis:
    image: "redis"
  rabitmq:
    image: "rabbitmq"
  worker:
    hostname: worker
    environment:
      APP_BROKER_URI: "pyamqp://guest@rabitmq:5672"
      APP_BACKEND: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    build:
      context: .
    entrypoint: poetry
    command: run celery -A app.celery worker --loglevel=info
    links:
      - redis
      - rabitmq
    depends_on:
      - redis
      - rabitmq
    volumes:
      - .:/code
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      # - ./nginx/certificates/:/etc/nginx/ssl/
