services:
  web:
    build: .
    depends_on:
      - redis
      - rabitmq
      - worker
    environment:
      - FLASK_ENV=development
    ports:
      - "6000:5000"
    entrypoint: poetry
    command: run flask run
  redis:
    image: "redis"
  rabitmq:
    image: "rabbitmq"
    ports:
      - "5672:5672"
  worker:
    build:
      context: .
    hostname: worker
    entrypoint: poetry
    command: run celery -A celery_app.celery worker --loglevel=info
    links:
      - redis
      - rabitmq
    depends_on:
      - redis
      - rabitmq
